services:
    newscoop_editor.configure_menu_listener:
        class: Newscoop\EditorBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    newscoop_editor.lifecyclesubscriber:
        class: Newscoop\EditorBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
            - @fos_oauth_server.client_manager.default
            - @system_preferences_service
            - @translator
            - @newscoop.plugins.service
        tags:
            - { name: kernel.event_subscriber}

    newscoop_editor.editor_service:
        class: Newscoop\EditorBundle\Services\EditorService
        arguments:  ["@em", "@user", "@newscoop.cache"]

    newscoop_editor.hooks.listener:
        class: "Newscoop\EditorBundle\EventListener\EditorListener"
        arguments: ["@newscoop.plugins.service", "@router", "@user", "@em"]
        tags:
          - { name: kernel.event_listener, event: newscoop_admin.editor, method: generateEditorLink }


    newscoop_editor.permissions.listener:
        class: Newscoop\EditorBundle\EventListener\PermissionsListener
        arguments:
            - @translator
        tags:
          - { name: kernel.event_listener, event: newscoop.plugins.permissions.register, method: registerPermissions }